//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace DoenaSoft.DVDProfiler.EnhancedTitles
{
    using System.Xml.Serialization;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class EnhancedTitles
    {

        private Text internationalEnglishTitleField;

        private Text alternateOriginalTitleField;

        private Text nonLatinLettersTitleField;

        private Text additionalTitle1Field;

        private Text additionalTitle2Field;

        private InvelosData invelosDataField;

        /// <remarks/>
        public Text InternationalEnglishTitle
        {
            get
            {
                return this.internationalEnglishTitleField;
            }
            set
            {
                this.internationalEnglishTitleField = value;
            }
        }

        /// <remarks/>
        public Text AlternateOriginalTitle
        {
            get
            {
                return this.alternateOriginalTitleField;
            }
            set
            {
                this.alternateOriginalTitleField = value;
            }
        }

        /// <remarks/>
        public Text NonLatinLettersTitle
        {
            get
            {
                return this.nonLatinLettersTitleField;
            }
            set
            {
                this.nonLatinLettersTitleField = value;
            }
        }

        /// <remarks/>
        public Text AdditionalTitle1
        {
            get
            {
                return this.additionalTitle1Field;
            }
            set
            {
                this.additionalTitle1Field = value;
            }
        }

        /// <remarks/>
        public Text AdditionalTitle2
        {
            get
            {
                return this.additionalTitle2Field;
            }
            set
            {
                this.additionalTitle2Field = value;
            }
        }

        /// <remarks/>
        public InvelosData InvelosData
        {
            get
            {
                return this.invelosDataField;
            }
            set
            {
                this.invelosDataField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Text
    {

        private string displayNameField;

        private string base64DisplayNameField;

        private string base64TitleField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DisplayName
        {
            get
            {
                return this.displayNameField;
            }
            set
            {
                this.displayNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Base64DisplayName
        {
            get
            {
                return this.base64DisplayNameField;
            }
            set
            {
                this.base64DisplayNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Base64Title
        {
            get
            {
                return this.base64TitleField;
            }
            set
            {
                this.base64TitleField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Profile
    {

        private EnhancedTitles enhancedTitlesField;

        private string idField;

        private string titleField;

        /// <remarks/>
        public EnhancedTitles EnhancedTitles
        {
            get
            {
                return this.enhancedTitlesField;
            }
            set
            {
                this.enhancedTitlesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InvelosData
    {

        private string titleField;

        private string sortTitleField;

        private string originalTitleField;

        /// <remarks/>
        public string Title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }

        /// <remarks/>
        public string SortTitle
        {
            get
            {
                return this.sortTitleField;
            }
            set
            {
                this.sortTitleField = value;
            }
        }

        /// <remarks/>
        public string OriginalTitle
        {
            get
            {
                return this.originalTitleField;
            }
            set
            {
                this.originalTitleField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class EnhancedTitlesList
    {

        private Profile[] profilesField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public Profile[] Profiles
        {
            get
            {
                return this.profilesField;
            }
            set
            {
                this.profilesField = value;
            }
        }
    }
}